#!/bin/bash
# scripts/setup-env.sh
# Run via: npm run setup:env
# Idempotent — safe to re-run

set -euo pipefail

ENV_FILE=".env.local"
EXAMPLE_FILE=".env.example"

echo ""
echo "🔧 SecureStack Environment Setup"
echo "═══════════════════════════════════"

# Guard: don't overwrite existing config without confirmation
if [ -f "$ENV_FILE" ]; then
  read -rp "⚠️  .env.local already exists. Overwrite? (y/N): " confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }
fi

# Check for openssl (needed for secret generation)
command -v openssl >/dev/null 2>&1 || {
  echo "❌ openssl not found. Install it and re-run."
  exit 1
}

# ─── Collect inputs ───────────────────────────────────────────────────────────

echo ""
echo "📦 Database Configuration"
DEFAULT_DB="postgresql://postgres:postgres@localhost:5432/securestack?sslmode=disable"
read -rp "DATABASE_URL [$DEFAULT_DB]: " db_url
db_url="${db_url:-$DEFAULT_DB}"

echo ""
echo "🔐 Generating cryptographic secrets..."
jwt_secret=$(openssl rand -hex 32)
encryption_key=$(openssl rand -hex 64)

# ─── Write .env.local ─────────────────────────────────────────────────────────

cat > "$ENV_FILE" << EOF
# Auto-generated by scripts/setup-env.sh on $(date)
# DO NOT commit this file — it is in .gitignore

# ── TIER 1: Required ──────────────────────────────────────────────
NEXT_PUBLIC_APP_URL=http://localhost:3000
DATABASE_URL="${db_url}"
JWT_SECRET="${jwt_secret}"
ENCRYPTION_KEY="${encryption_key}"

# ── TIER 2: Recommended (uncomment to enable features) ────────────
# RESEND_API_KEY=re_your_key_here
# EMAIL_FROM=noreply@example.com
# NEXT_PUBLIC_ALGOLIA_APP_ID=your_app_id
# NEXT_PUBLIC_ALGOLIA_SEARCH_KEY=your_search_key
# ALGOLIA_ADMIN_KEY=your_admin_key
# OPENAI_API_KEY=sk-proj-your_key_here

# ── TIER 3: Optional (monitoring, not needed locally) ─────────────
# NEXT_PUBLIC_SENTRY_DSN=your_dsn
# UPSTASH_REDIS_REST_URL=your_url
# UPSTASH_REDIS_REST_TOKEN=your_token
EOF

echo ""
echo "✅ .env.local created."
echo ""
echo "Next step: npm run db:up"
echo ""
